name: Phase

on: [push, pull_request]

jobs:
  production-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "copy('.env.actions.example', '.env');"
    - name: Install PHP Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run prod
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Save Production Build
        branch: ${{ github.head_ref }}
